name: Deploy Package
on:
  push:
    branches: [main, chore-publish-package]

jobs:
  build:
    uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@chore-add-publish-npm
    with:
      package_manager: npm
      package_folder: build

  coverage:
    needs: build
    uses: flexbase-eng/.github/.github/workflows/typescript.sonarcloud.yml@chore-add-publish-npm
    with:
      project_key: flexbase-eng_persona-node-client
    secrets: inherit

  publish:
    needs: coverage
    uses: flexbase-eng/.github/.github/workflows/typescript.publish.npm.yml@chore-add-publish-npm
    with: 
      package_manager: npm
      tag: beta
    secrets: inherit
